"""apply — turn findings into hot-swappable capabilities.

The self-improvement loop:
  - 'skill'     finding  -> generated-skills/<slug>/SKILL.md   (hot-swappable)
  - 'alert'     finding  -> generated-alerts/<slug>.json       (watchdog config)
  - 'config_fix' finding -> generated-fixes/<slug>.patch       (draft patch)
All artifacts are data-driven, reviewable, and consumed by agents via MCP.
"""
from __future__ import annotations

import json
import os
import re
from typing import Dict, List, Optional

from . import core

SKILLS_DIR = os.environ.get(
    "MYCELIUM_SKILLS_DIR", os.path.expanduser("~/mycelium/generated-skills")
)
ALERTS_DIR = os.environ.get(
    "MYCELIUM_ALERTS_DIR", os.path.expanduser("~/mycelium/generated-alerts")
)
FIXES_DIR = os.environ.get(
    "MYCELIUM_FIXES_DIR", os.path.expanduser("~/mycelium/generated-fixes")
)

SLUG_BLOCKLIST = {"", "none", "null", "unknown"}


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "_", text.lower()).strip("_")
    return slug[:60] or "finding"


def _sequence_to_steps(sequence: List[str]) -> str:
    steps = []
    for i, act in enumerate(sequence, 1):
        steps.append(f"{i}. Invoke `{act}` (the discovered next step in this workflow).")
    return "\n".join(steps)


def generate_skill(finding: Dict[str, Any]) -> Dict[str, str]:
    """Render a finding into a SKILL.md on disk. Returns {path, slug}."""
    payload = finding.get("payload") or {}
    seq: List[str] = payload.get("sequence") or []
    slug = _slugify(
        payload.get("slug")
        or ("_".join(seq) if len(seq) > 1 else (seq[0] if seq else "compound_workflow"))
    )
    if slug in SLUG_BLOCKLIST:
        slug = "compound_workflow"
    title = finding.get("title", "Compound workflow skill")
    evidence = finding.get("evidence", "")
    confidence = finding.get("confidence", 0.0)
    steps = _sequence_to_steps(seq) if seq else "1. Execute the workflow steps in order."

    body = f"""---
name: {slug}
description: Auto-generated by Mycelium from a recurring agent workflow (confidence {confidence:.2f}). Detected sequence: {' -> '.join(seq) or 'n/a'}.
---

# {title}

## Origin
Discovered by the Mycelium substrate — evidence: {evidence}

## Steps
{steps}

## When to use
Trigger when the same multi-step sequence starts recurring. This skill collapses
the raw calls into one compound invocation.

## Pitfalls
- Re-verify each step's output before proceeding; the pattern was learned from
  successful past runs but the environment may have changed.
"""
    path = os.path.join(SKILLS_DIR, slug, "SKILL.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(body)
    return {"path": path, "slug": slug}


def generate_alert(finding: Dict[str, Any]) -> Dict[str, str]:
    """Render a finding into a watchdog alert config (JSON, data-driven).

    The config is declarative: the mycelium alert runner evaluates conditions
    against the substrate (never arbitrary shell). Any agent can consume it.
    """
    payload = finding.get("payload") or {}
    action = payload.get("action") or "?"
    slug = _slugify(f"alert_{action}")
    config = {
        "finding_id": finding.get("id", ""),
        "miner": finding.get("miner", ""),
        "confidence": finding.get("confidence", 0.0),
        "created_ts": finding.get("created_ts", core._now()),
        "condition": {
            "metric": "error_rate",
            "action": action,
            "min_failures": int(payload.get("failures", 3)),
            "min_rate": float(payload.get("rate", 0.5)),
        },
        "evidence": finding.get("evidence", ""),
        "state": "armed",
    }
    path = os.path.join(ALERTS_DIR, f"{slug}.json")
    os.makedirs(ALERTS_DIR, exist_ok=True)
    with open(path, "w") as fh:
        json.dump(config, fh, indent=2)
    return {"path": path, "slug": slug}


def generate_config_fix(finding: Dict[str, Any]) -> Dict[str, str]:
    """Render a finding into a draft patch (generated-fixes/<slug>.patch).

    Draft only — a review agent applies it. The draft carries the evidence
    and a concrete suggested change derived from the finding payload.
    """
    payload = finding.get("payload") or {}
    action = payload.get("action") or "?"
    target = payload.get("target") or "?"
    agents = ", ".join(payload.get("agents") or [])
    slug = _slugify(f"fix_{action}_{target}")
    patch = f"""--- a/config/shared
+++ b/config/shared
@@ draft generated by Mycelium from finding {finding.get('id', '?')} @@
 #
 # Evidence: {finding.get('evidence', '')}
 #
 # Suggested change (REVIEW BEFORE APPLYING):
 #   Cross-agent failures on '{action}' target='{target}' were observed from
 #   agents: {agents or 'unknown'}. This pattern points at a SHARED
 #   credential/config, not per-agent code. Verify and rotate the shared
 #   credential, then re-run the affected agents.
 #
-# TODO: apply the concrete change after review
+# VERIFY: shared credential for '{action}' -> '{target}' is valid on all agents
"""
    path = os.path.join(FIXES_DIR, f"{slug}.patch")
    os.makedirs(FIXES_DIR, exist_ok=True)
    with open(path, "w") as fh:
        fh.write(patch)
    return {"path": path, "slug": slug}


def apply_finding(finding_id: str) -> Optional[Dict[str, str]]:
    """Apply an open finding. Returns artifact info, or None if not applicable."""
    row = core.get_finding(finding_id)
    if not row:
        return None
    f = core.row_to_dict(row)
    if f["state"] != "open":
        return {"error": f"finding already {f['state']}"}
    suggestion = f.get("suggestion", "")
    if suggestion == "skill":
        info = generate_skill(f)
        core.set_finding_state(finding_id, "applied")
        info["finding_id"] = finding_id
        return info
    if suggestion == "alert":
        info = generate_alert(f)
        core.set_finding_state(finding_id, "applied")
        info["finding_id"] = finding_id
        return info
    if suggestion == "config_fix":
        info = generate_config_fix(f)
        core.set_finding_state(finding_id, "applied")
        info["finding_id"] = finding_id
        return info
    return {"error": f"suggestion type '{suggestion}' not wired"}
