"""larql_client.py — opt-in bridge from Mycelium miners to a local larql server.

When LARQL_ENABLED=1 is set, findings generated by Mycelium miners are
forwarded to larql's OpenAI-compatible /v1/chat/completions endpoint so that
larql can enrich, classify, or reformat them before final storage.

Design:
  - Completely opt-in; if LARQL_ENABLED is not set (or is "0"/"false"),
    every call in this module is a no-op that returns the input unchanged.
  - The enrichment is best-effort: if larql is unreachable or returns an
    error, the original finding passes through unchanged.
  - LARQL_SERVER_URL defaults to http://localhost:8080 (larql-server default).
"""
from __future__ import annotations

import json
import os
import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

_ENABLED: bool | None = None  # lazily evaluated


def _is_enabled() -> bool:
    global _ENABLED
    if _ENABLED is None:
        v = os.environ.get("LARQL_ENABLED", "0").strip().lower()
        _ENABLED = v in ("1", "true", "yes")
    return _ENABLED


def _server_url() -> str:
    return os.environ.get("LARQL_SERVER_URL", "http://localhost:8080").rstrip("/")


def _model() -> str:
    return os.environ.get("LARQL_MODEL", "larql-default")


async def enrich_finding(finding: dict[str, Any]) -> dict[str, Any]:
    """
    Send a raw finding dict to larql for enrichment.

    Returns the enriched finding (or the original on any failure).
    The enriched content is expected as a JSON object in the assistant reply.
    """
    if not _is_enabled():
        return finding

    prompt = (
        "You are a sovereign-ecosystem finding analyst. "
        "Given this raw finding, return an enriched JSON object with fields: "
        "title, summary, severity (low/medium/high/critical), tags (list), "
        "suggested_action.\n\nRaw finding:\n" + json.dumps(finding, indent=2)
    )

    payload = {
        "model": _model(),
        "messages": [{"role": "user", "content": prompt}],
        "response_format": {"type": "json_object"},
        "temperature": 0.2,
    }

    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.post(
                f"{_server_url()}/v1/chat/completions",
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"]
            enriched = json.loads(content)
            # Merge enrichment into a copy of the original finding.
            return {**finding, **enriched, "_larql_enriched": True}
    except Exception as exc:
        logger.debug("larql enrichment skipped: %s", exc)
        return finding


async def classify_finding_direction(finding: dict[str, Any]) -> int:
    """
    Ask larql to classify whether a finding is improving (+1), neutral (0),
    or regressing (-1) relative to the sovereign ecosystem baseline.

    Returns int in {-1, 0, 1}.  Defaults to 0 on any failure.
    """
    if not _is_enabled():
        return 0

    prompt = (
        "Classify this finding as improving (+1), neutral (0), or regressing (-1) "
        "for the sovereign ecosystem. Reply with ONLY the integer.\n\n"
        "Finding: " + json.dumps(finding, indent=2)
    )

    payload = {
        "model": _model(),
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 5,
        "temperature": 0.0,
    }

    try:
        async with httpx.AsyncClient(timeout=8) as client:
            resp = await client.post(
                f"{_server_url()}/v1/chat/completions",
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()
            raw = data["choices"][0]["message"]["content"].strip()
            val = int(raw)
            if val not in (-1, 0, 1):
                return 0
            return val
    except Exception as exc:
        logger.debug("larql direction classification skipped: %s", exc)
        return 0
