"""larql_client.py — opt-in bridge from Mycelium miners to a local larql server.

When LARQL_ENABLED=1 is set, findings generated by Mycelium miners are
forwarded to larql's native /v1/infer endpoint (BitNet b1.58 GGUF,
native-ternary path) for semantic classification before final storage.

The module also exposes an OpenAI-compatible enrichment path
(enrich_finding / classify_finding_direction → /v1/chat/completions) used
by core.async_add_finding. Both paths are guarded by the same
LARQL_ENABLED flag and fail-open on any error.

Design:
  - Completely opt-in; if LARQL_ENABLED is not set (or is "0"/"false"),
    every call in this module is a no-op that returns the input unchanged.
  - The enrichment is best-effort: if larql is unreachable or returns an
    error, the original finding passes through unchanged (fail-open).
  - LARQL_URL (preferred) or LARQL_SERVER_URL default to
    http://localhost:7780 (larql-server BitNet default per the spec).
    LARQL_SERVER_URL is kept for back-compat; LARQL_URL takes precedence.

Environment variables:
  LARQL_ENABLED      "1"/"true"/"yes" to activate (default off)
  LARQL_URL          Base URL for larql server (default http://localhost:7780)
  LARQL_SERVER_URL   Alias for LARQL_URL (legacy; LARQL_URL takes precedence)
  LARQL_MODEL        Model name for /v1/chat/completions path (default bitnet-b1.58)
  LARQL_TIMEOUT      HTTP timeout in seconds (default 5.0)
"""
from __future__ import annotations

import json
import os
import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

_ENABLED: bool | None = None  # lazily evaluated

# ------------------------------------------------------------------ config

LARQL_TIMEOUT = float(os.getenv("LARQL_TIMEOUT", "5.0"))


def _is_enabled() -> bool:
    global _ENABLED
    if _ENABLED is None:
        v = os.environ.get("LARQL_ENABLED", "0").strip().lower()
        _ENABLED = v in ("1", "true", "yes")
    return _ENABLED

# Re-exported as a module-level bool so callers can do a cheap guard
# without calling the function (e.g. `if LARQL_ENABLED: ...`).
# Evaluated at import time after the function is defined.
LARQL_ENABLED: bool = _is_enabled()


def _server_url() -> str:
    # LARQL_URL takes precedence; LARQL_SERVER_URL is the legacy alias.
    url = (
        os.environ.get("LARQL_URL")
        or os.environ.get("LARQL_SERVER_URL")
        or "http://localhost:7780"
    )
    return url.rstrip("/")


def _model() -> str:
    return os.environ.get("LARQL_MODEL", "bitnet-b1.58")


async def enrich_finding(finding: dict[str, Any]) -> dict[str, Any]:
    """
    Send a raw finding dict to larql for enrichment.

    Returns the enriched finding (or the original on any failure).
    The enriched content is expected as a JSON object in the assistant reply.
    """
    if not _is_enabled():
        return finding

    prompt = (
        "You are a sovereign-ecosystem finding analyst. "
        "Given this raw finding, return an enriched JSON object with fields: "
        "title, summary, severity (low/medium/high/critical), tags (list), "
        "suggested_action.\n\nRaw finding:\n" + json.dumps(finding, indent=2)
    )

    payload = {
        "model": _model(),
        "messages": [{"role": "user", "content": prompt}],
        "response_format": {"type": "json_object"},
        "temperature": 0.2,
    }

    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.post(
                f"{_server_url()}/v1/chat/completions",
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"]
            enriched = json.loads(content)
            # Merge enrichment into a copy of the original finding.
            return {**finding, **enriched, "_larql_enriched": True}
    except Exception as exc:
        logger.debug("larql enrichment skipped: %s", exc)
        return finding


async def classify_finding_direction(finding: dict[str, Any]) -> int:
    """
    Ask larql to classify whether a finding is improving (+1), neutral (0),
    or regressing (-1) relative to the sovereign ecosystem baseline.

    Returns int in {-1, 0, 1}.  Defaults to 0 on any failure.
    """
    if not _is_enabled():
        return 0

    prompt = (
        "Classify this finding as improving (+1), neutral (0), or regressing (-1) "
        "for the sovereign ecosystem. Reply with ONLY the integer.\n\n"
        "Finding: " + json.dumps(finding, indent=2)
    )

    payload = {
        "model": _model(),
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 5,
        "temperature": 0.0,
    }

    try:
        async with httpx.AsyncClient(timeout=8) as client:
            resp = await client.post(
                f"{_server_url()}/v1/chat/completions",
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()
            raw = data["choices"][0]["message"]["content"].strip()
            val = int(raw)
            if val not in (-1, 0, 1):
                return 0
            return val
    except Exception as exc:
        logger.debug("larql direction classification skipped: %s", exc)
        return 0


# ── /v1/infer  — native-ternary BitNet b1.58 path (gap #42) ──────────────────
#
# These three functions target larql's dedicated /v1/infer endpoint, which
# routes directly to the native-ternary inference path for BitNet b1.58
# GGUF models (GGML type 36 / I2_S quantization).  Unlike the
# /v1/chat/completions path above (which works with any OpenAI-compat model
# and produces free-text JSON), /v1/infer expects a structured `schema`
# field and returns a typed JSON object — cheaper, faster, and deterministic
# for the ternary direction+confidence classification task.
#
# classify_finding       — async, single finding
# classify_batch         — async, list of findings
# classify_finding_sync  — sync wrapper for non-async callers (cli.py miners)


async def classify_finding(
    trace_content: str,
    existing_confidence: float = 0.5,
    existing_direction: int = 0,
) -> dict[str, Any]:
    """Send trace content to larql /v1/infer for semantic classification.

    Returns enriched {confidence, direction, label, explanation,
    larql_enriched} or original values on failure (fail-open).

    direction semantics: -1=deteriorating, 0=neutral, +1=improving.
    """
    if not _is_enabled():
        return {
            "confidence": existing_confidence,
            "direction": existing_direction,
            "label": None,
            "explanation": None,
            "larql_enriched": False,
        }

    try:
        async with httpx.AsyncClient(timeout=LARQL_TIMEOUT) as client:
            resp = await client.post(
                f"{_server_url()}/v1/infer",
                json={
                    "input": trace_content,
                    "task": "classify_finding",
                    "schema": {
                        "confidence": "float 0-1",
                        "direction": "int -1/0/+1 (deteriorating/neutral/improving)",
                        "label": "string category",
                        "explanation": "string one-sentence",
                    },
                },
            )
            if resp.status_code == 200:
                body = resp.json()
                return {
                    "confidence": float(body.get("confidence", existing_confidence)),
                    "direction": int(body.get("direction", existing_direction)),
                    "label": body.get("label"),
                    "explanation": body.get("explanation"),
                    "larql_enriched": True,
                }
    except Exception as exc:
        logger.debug("larql /v1/infer classify_finding skipped: %s", exc)

    return {
        "confidence": existing_confidence,
        "direction": existing_direction,
        "label": None,
        "explanation": None,
        "larql_enriched": False,
    }


async def classify_batch(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Batch classify findings via larql /v1/infer/batch.

    Each item must have keys: content (str), confidence (float),
    direction (int).  Falls back to originals (larql_enriched=False) on
    any error or length mismatch.
    """
    if not _is_enabled():
        return [{**item, "larql_enriched": False} for item in items]

    try:
        async with httpx.AsyncClient(timeout=LARQL_TIMEOUT) as client:
            resp = await client.post(
                f"{_server_url()}/v1/infer/batch",
                json={"items": items, "task": "classify_finding"},
            )
            if resp.status_code == 200:
                results = resp.json().get("results", [])
                if len(results) == len(items):
                    return [
                        {**item, **result, "larql_enriched": True}
                        for item, result in zip(items, results)
                    ]
    except Exception as exc:
        logger.debug("larql /v1/infer/batch skipped: %s", exc)

    return [{**item, "larql_enriched": False} for item in items]


def classify_finding_sync(
    trace_content: str,
    existing_confidence: float = 0.5,
    existing_direction: int = 0,
) -> dict[str, Any]:
    """Synchronous variant of classify_finding for non-async callers.

    Uses httpx.post (blocking).  Same fail-open contract: returns original
    values if LARQL_ENABLED is false or larql is unreachable.
    """
    if not _is_enabled():
        return {
            "confidence": existing_confidence,
            "direction": existing_direction,
            "larql_enriched": False,
        }

    try:
        resp = httpx.post(
            f"{_server_url()}/v1/infer",
            json={
                "input": trace_content,
                "task": "classify_finding",
                "schema": {
                    "confidence": "float 0-1",
                    "direction": "int -1/0/+1 (deteriorating/neutral/improving)",
                    "label": "string category",
                    "explanation": "string one-sentence",
                },
            },
            timeout=LARQL_TIMEOUT,
        )
        if resp.status_code == 200:
            body = resp.json()
            return {
                "confidence": float(body.get("confidence", existing_confidence)),
                "direction": int(body.get("direction", existing_direction)),
                "label": body.get("label"),
                "explanation": body.get("explanation"),
                "larql_enriched": True,
            }
    except Exception as exc:
        logger.debug("larql /v1/infer sync classify_finding skipped: %s", exc)

    return {
        "confidence": existing_confidence,
        "direction": existing_direction,
        "larql_enriched": False,
    }
